dist: bionic
sudo: required
addons:
  apt:
    packages:
    - qemu
    - qemu-user-static
    - binfmt-support
    - parted
    - wget
    - dosfstools
    - zip
script:
- sudo bash ./create-image
- zip $(basename $TRAVIS_REPO_SLUG).img.zip $(basename $TRAVIS_REPO_SLUG).img
- shasum $(basename $TRAVIS_REPO_SLUG).img.zip > $(basename $TRAVIS_REPO_SLUG).img.zip.sha1
deploy:
  provider: releases
  api_key:
    secure: GHc5BhfgbmFjc1aVDNEr9qZR8Omv/XUZYwP+Jb+h2egIvFQR9VbugXOP3PlWq6qWtsENWEgZlw88wnlC5LYVL3Ww+ln2bGrZx09d4FreP1dv0Jy23poPF5t1FOpUUMQ80rqxiTsSGusMoW/RQTEUZV4XDspRG+Rntjd49cgnCwoqZYJBVM3mlVVzyClvQZqHrCwFwXotc4vmADwlr7SgvIKl6fLAcGGCQgrgn+Yv2DgqTnmj8Acko1Clk4V8GDRrsxGFdUPX65k7p11RZNyjx25/zFblKtW0rRx98rCKf9rkbNcJVlGA8LN3xYju0KVuVvC3HoQgYPtwmmJBONtlyiof/2mCIz/6wsY8cerESTOlxwkfeG5r+dSShb7VivQgsGrQs9yU8V9FRqQUPilW4RvZOY3dq3XUvcB9p+7tTjU2jZiDLvqLkS0xMo01d+ZfONEOAVsvDhcbjNhSeJ4QS3pKp5qQ4L9rhhelvdTTZhfOIsDR+Gj5uqvGTl8ucLrT5kzZ70sEao2nwitdmOIMpTzFxFhJbMgiCBBXAujAQA7a3nqZQ5MSLdiojgjMoxWIJVDO0xhC9RRTzeNK/lv6iNmNqxu1ULmjwEvdoNQeCq2wdwQsqN5ZhBaztGbgxzNEHTVz7DvVZRNJIxNqaW1sI7R631eSSgplivNlbXXRDNk=
  file: 
    - "$(basename $TRAVIS_REPO_SLUG).img.zip"
    - "$(basename $TRAVIS_REPO_SLUG).img.zip.sha1"
skip_cleanup: true
on:
  tags: true