#!/bin/bash

echo "Hello. This is setup."

# Replace /boot/cmdline.txt since it contains root device mapping to a PARTUUID that 
# changed during parted resize. We try to disable the autoresize here as well.
echo "Replace /boot/cmdline.txt"
echo "dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet" > "${mount}/boot/cmdline.txt"
cat "${mount}/boot/cmdline.txt"

# Replace /etc/fstab since the non existing PARTUUID has to be changed here as well.
echo "Replace /etc/fstab"
echo "proc            /proc           proc    defaults          0       0" > "${mount}/etc/fstab"
echo "/dev/mmcblk0p1  /boot           vfat    defaults          0       2" >> "${mount}/etc/fstab"
echo "/dev/mmcblk0p2  /               ext4    defaults,noatime  0       1" >> "${mount}/etc/fstab"
cat "${mount}/etc/fstab"

# Disable automatic filesystem expansion on boot
#rm /usr/lib/raspi-config/init_resize.sh
rm /etc/init.d/resize2fs_once
rm /etc/rc3.d/S01resize2fs_once

echo "Installing packages."
apt-get -y update
apt-get -y install git batctl

echo "Load batman-adv kernel module at boot"
echo 'batman-adv' | sudo tee --append /etc/modules

echo "Disable DHCPD on wlan0"
echo 'denyinterfaces wlan0' | sudo tee --append /etc/dhcpcd.conf

echo "Add Network configuration files"
# bat0
echo "auto bat0" > "${mount}/etc/network/interfaces.d/bat0"
echo "iface bat0 inet auto" >> "${mount}/etc/network/interfaces.d/bat0"
echo "    pre-up /usr/sbin/batctl if add wlan0" >> "${mount}/etc/network/interfaces.d/bat0"
# wlan0
echo "auto wlan0" > "${mount}/etc/network/interfaces.d/wlan0"
echo "iface wlan0 inet manual" >> "${mount}/etc/network/interfaces.d/wlan0"
echo "    mtu 1532" >> "${mount}/etc/network/interfaces.d/wlan0"
echo "    wireless-channel 1" >> "${mount}/etc/network/interfaces.d/wlan0"
echo "    wireless-essid game-mesh" >> "${mount}/etc/network/interfaces.d/wlan0"
echo "    wireless-mode ad-hoc" >> "${mount}/etc/network/interfaces.d/wlan0"
echo "    wireless-ap 6a:2b:90:3b:54:98" >> "${mount}/etc/network/interfaces.d/wlan0"

echo "Add startscript for batman"
echo "#!/bin/bash" > "${mount}/home/pi/start-batman-adv.sh"
echo "sudo batctl if add wlan0" >> "${mount}/home/pi/start-batman-adv.sh"
echo "sudo ifconfig wlan0 up" >> "${mount}/home/pi/start-batman-adv.sh"
echo "sudo ifconfig bat0 up" >> "${mount}/home/pi/start-batman-adv.sh"
chmod +x "${mount}/home/pi/start-batman-adv.sh"

echo "Add service"
echo "[Unit]" > "${mount}/etc/systemd/system/start-batman-adv"
echo "Description=Start batman-adv" >> "${mount}/etc/systemd/system/start-batman-adv"
echo "[Service]" >> "${mount}/etc/systemd/system/start-batman-adv"
echo "Type=simple" >> "${mount}/etc/systemd/system/start-batman-adv"
echo "ExecStart=/home/pi/start-batman-adv.sh" >> "${mount}/etc/systemd/system/start-batman-adv"
echo "[Install]" >> "${mount}/etc/systemd/system/start-batman-adv"
echo "WantedBy=multi-user.target" >> "${mount}/etc/systemd/system/start-batman-adv"
systemctl daemon-reload
systemctl enable start-batman-adv

echo "Congratulations! Your custom Raspbian is ready!"

echo "Disk space"
df -h